apiVersion: apps/v1
kind: Deployment
metadata:
  name:  beer-provider
  namespace: default
  labels:
    app:  beer-provider

spec:
  selector:
    matchLabels:
      app: beer-provider
  
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  beer-provider
    
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  beer
        image:  beer-provider
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 700m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  8081
          name:  beer-provider