apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: beer-domain

images:
- name: beer
  newName: beer-provider
- name: beer-provider
  newName: rscoelho/beer-provider
  newTag: ""
