apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: beer-domain

images:
- name: beer-provider
  newName: rscoelho/beer_provider
  newTag: 25eb2948cbb94ca349c435fd39aabad1127ed122
