apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- monitor.yml

namespace: beer-domain

images:
- name: beer-provider
  newName: rscoelho/beer_provider
  newTag: 1a0418af4dc89ecae0d1e3b5d406d1d7aba1941b
