apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: beer_domain

images:
- name: beer
  newName: beer_provider
- name: beer_provider
  newName: rscoelho/beer_provider
  newTag: "12321"
