apiVersion: v1
kind: Service
metadata:
  name: beer-provider
  namespace: default
spec:
  selector:
    app: beer-provider
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: beer-provider
    protocol: TCP
    port: 8081
    targetPort: 8081
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    #nodePort: 8081