name: Continuous Integration Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Grant execute permission for gradle wrapper
        run: chmod +x gradlew

      - name: Clean
        run: ./gradlew clean test

      - name: Build
        run: ./gradlew build -x test

      - name: Generate Contract Test
        run: ./gradlew generateContractTests

      - name: Run test
        run: ./gradlew test


